apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-config
  namespace: gitea
data:
  app.ini: |
    APP_NAME = Arthur's Git
    RUN_MODE = prod

    [server]
    DOMAIN             = git.arthurbarre.fr
    ROOT_URL           = https://git.arthurbarre.fr/
    HTTP_PORT          = 3000
    SSH_DOMAIN         = git.arthurbarre.fr
    SSH_PORT           = 2222
    SSH_LISTEN_PORT    = 2222
    LFS_START_SERVER   = true

    [database]
    DB_TYPE  = postgres
    HOST     = 10.10.10.3:5432
    NAME     = gitea
    USER     = gitea
    PASSWD   = __GITEA_DB_PASSWORD__
    SSL_MODE = disable

    [session]
    PROVIDER = db

    [cache]
    ADAPTER = memory

    [log]
    MODE  = console
    LEVEL = info

    [security]
    INSTALL_LOCK   = true
    SECRET_KEY     = __CHANGE_ME_SECRET_KEY__
    INTERNAL_TOKEN = __CHANGE_ME_INTERNAL_TOKEN__

    [service]
    DISABLE_REGISTRATION       = false
    REQUIRE_SIGNIN_VIEW        = false
    REGISTER_EMAIL_CONFIRM     = false
    ENABLE_NOTIFY_MAIL         = false
    DEFAULT_KEEP_EMAIL_PRIVATE = true

    [packages]
    ENABLED = true

    [actions]
    ENABLED    = true
    DEFAULT_ACTIONS_URL = github

    [repository]
    DEFAULT_BRANCH = main
    ENABLE_PUSH_CREATE_USER = true
    ENABLE_PUSH_CREATE_ORG  = true

    [lfs]
    STORAGE_TYPE = local
    PATH         = /var/lib/gitea/data/lfs
