apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-config
  namespace: gitea
data:
  app.ini: |
    APP_NAME = Arthur's Git
    RUN_MODE = prod

    [server]
    DOMAIN             = git.arthurbarre.fr
    ROOT_URL           = https://git.arthurbarre.fr/
    HTTP_PORT          = 3000
    SSH_DOMAIN         = git.arthurbarre.fr
    SSH_PORT           = 2222
    SSH_LISTEN_PORT    = 2222
    LFS_START_SERVER   = true

    [database]
    DB_TYPE  = postgres
    HOST     = 10.10.10.3:5432
    NAME     = gitea
    USER     = gitea
    PASSWD   = __GITEA_DB_PASSWORD__
    SSL_MODE = disable

    [session]
    PROVIDER = db

    [cache]
    ADAPTER = memory

    [log]
    MODE  = console
    LEVEL = info

    [security]
    INSTALL_LOCK   = true
    SECRET_KEY     = __CHANGE_ME_SECRET_KEY__
    INTERNAL_TOKEN = __CHANGE_ME_INTERNAL_TOKEN__

    [service]
    DISABLE_REGISTRATION       = false
    REQUIRE_SIGNIN_VIEW        = false
    REGISTER_EMAIL_CONFIRM     = false
    ENABLE_NOTIFY_MAIL         = false
    DEFAULT_KEEP_EMAIL_PRIVATE = true

    [packages]
    ENABLED = true

    [actions]
    ENABLED    = true
    DEFAULT_ACTIONS_URL = github

    [repository]
    DEFAULT_BRANCH = main
    ENABLE_PUSH_CREATE_USER = true
    ENABLE_PUSH_CREATE_ORG  = true

    [lfs]
    STORAGE_TYPE = local
    PATH         = /var/lib/gitea/data/lfs

    [ui]
    THEMES = gitea-auto,gitea-light,gitea-dark,catppuccin-latte-rosewater,catppuccin-latte-flamingo,catppuccin-latte-pink,catppuccin-latte-mauve,catppuccin-latte-red,catppuccin-latte-maroon,catppuccin-latte-peach,catppuccin-latte-yellow,catppuccin-latte-green,catppuccin-latte-teal,catppuccin-latte-sky,catppuccin-latte-sapphire,catppuccin-latte-blue,catppuccin-latte-lavender,catppuccin-frappe-rosewater,catppuccin-frappe-flamingo,catppuccin-frappe-pink,catppuccin-frappe-mauve,catppuccin-frappe-red,catppuccin-frappe-maroon,catppuccin-frappe-peach,catppuccin-frappe-yellow,catppuccin-frappe-green,catppuccin-frappe-teal,catppuccin-frappe-sky,catppuccin-frappe-sapphire,catppuccin-frappe-blue,catppuccin-frappe-lavender,catppuccin-macchiato-rosewater,catppuccin-macchiato-flamingo,catppuccin-macchiato-pink,catppuccin-macchiato-mauve,catppuccin-macchiato-red,catppuccin-macchiato-maroon,catppuccin-macchiato-peach,catppuccin-macchiato-yellow,catppuccin-macchiato-green,catppuccin-macchiato-teal,catppuccin-macchiato-sky,catppuccin-macchiato-sapphire,catppuccin-macchiato-blue,catppuccin-macchiato-lavender,catppuccin-mocha-rosewater,catppuccin-mocha-flamingo,catppuccin-mocha-pink,catppuccin-mocha-mauve,catppuccin-mocha-red,catppuccin-mocha-maroon,catppuccin-mocha-peach,catppuccin-mocha-yellow,catppuccin-mocha-green,catppuccin-mocha-teal,catppuccin-mocha-sky,catppuccin-mocha-sapphire,catppuccin-mocha-blue,catppuccin-mocha-lavender,catppuccin-rosewater-auto,catppuccin-flamingo-auto,catppuccin-pink-auto,catppuccin-mauve-auto,catppuccin-red-auto,catppuccin-maroon-auto,catppuccin-peach-auto,catppuccin-yellow-auto,catppuccin-green-auto,catppuccin-teal-auto,catppuccin-sky-auto,catppuccin-sapphire-auto,catppuccin-blue-auto,catppuccin-lavender-auto
    DEFAULT_THEME = catppuccin-mocha-blue
