---
- name: Deploy node_exporter on all VMs
  hosts: gateway,databases,docker_hosts
  become: true
  roles:
    - node_exporter

- name: Deploy promtail on all VMs
  hosts: gateway,databases,docker_hosts
  become: true
  roles:
    - promtail
