apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: supabase-postgres-data
  namespace: supabase
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
